services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: doctech-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doctech
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - doctech-network

  # docTech Website (Next.js)
  doctech-website:
    build:
      context: ./docTech
      dockerfile: Dockerfile
    container_name: doctech-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=doctech
      - POSTGRES_SSL=false
      - NODE_ENV=development
    volumes:
      - product-images:/app/public/images/products
      - product-docs:/app/public/docs/products
    depends_on:
      - postgres
    networks:
      - doctech-network

  # docTech Dashboard (Vite)
  doctech-dashboard:
    build:
      context: ./docTech Dashboard
      dockerfile: Dockerfile
    container_name: doctech-dashboard
    restart: unless-stopped
    ports:
      - "5173:8080"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=doctech
      - POSTGRES_SSL=false
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5173
    volumes:
      - product-images:/app/public/images/products
      - product-docs:/app/public/docs/products
    depends_on:
      - postgres
    networks:
      - doctech-network

volumes:
  postgres-data:
  product-images:
  product-docs:

networks:
  doctech-network:
    driver: bridge
